management:
    security:
        enabled: false

graphql:
    servlet:
      mapping: /graphql
      enabled: true
      corsEnabled: true

graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true

spring:
    jpa:
      database: MYSQL
      hibernate:
        ddl-auto: update

    datasource:
      url: jdbc:mysql://mysql:3306/graphql
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver